
trigger:
  - develop

pool: "Default"

steps:
  - task: NodeTool@0
    displayName: "Install node"
    inputs:
      versionSpec: "16.x"

  - task: SonarCloudPrepare@1
    displayName: "Prepare SonarCloud"
    inputs:
      SonarCloud: 'SonarCloud'
      organization: 'mfbtech'
      scannerMode: 'CLI'
      configMode: 'manual'
      cliProjectKey: 'mfbtech_Syzygy_Web_App_align-ts_asyncRenderer'
      cliProjectName: 'TS Utils Async Renderer'
      cliSources: './utils/async-renderer'
      extraProperties: |
        sonar.project.monorepo.enabled=true
        sonar.exclusions=**/__tests__/**/*,**/__mocks__/**/*
        sonar.javascript.lcov.reportPaths=utils/async-renderer/coverage/lcov.info

  - task: npmAuthenticate@0
    inputs:
      workingFile: 'common/config/rush/.npmrc'

  - script: 'node common/scripts/install-run-rush.js install --bypass-policy'
    displayName: 'Rush: Install packages'

  - script: 'node common/scripts/install-run-rush.js rebuild --verbose --to @mfb/async-renderer'
    displayName: 'Rush: Build project and dependencies'

  - script: 'node ../../common/scripts/install-run-rushx.js test:azure'
    displayName: "Rush: Run unit tests"
    workingDirectory: 'utils/async-renderer'

  - task: SonarCloudAnalyze@1
    displayName: 'SonarCloud analysis'

  - task: SonarCloudPublish@1
    displayName: 'Publish SonarCloud analysis'
    inputs:
      pollingTimeoutSec: "300"

  - task: WhiteSource@21
    displayName: 'White source scan'
    inputs:
        cwd: '$(System.DefaultWorkingDirectory)/utils/async-renderer'
        projectName: 'TSAsyncRenderer'
