name: publish

# Run when a new Github publish is released
on: 
  release:
    types: [released]

jobs:
  publish:
    runs-on: ubuntu-latest
    steps:
      - name: Check out repository code
        uses: actions/checkout@v3
      
      - name: Setup node
        uses: actions/setup-node@v3
        with: 
          node-version: '16'
      
      - uses: JS-DevTools/npm-publish@v1
        with:
          token: ${{ secrets.NPM_TOKEN }}