name: publish

# Run when a new Github publish is released
on: 
  release:
    types: [released]

jobs:
  publish:
    runs-on: ubuntu-latest
    steps:
      - name: Check out repository code
        uses: actions/checkout@v3
      
      - name: Setup node
        uses: actions/setup-node@v3
        with: 
          node-version: '16'
      
      - name: Install packages
        run: npm install
      
      - name: Build project and dependencies
        run: npm run build
      
      - name: Run unit tests and generate report
        run: npm run test:ci

      - name: Publish package
        uses: JS-DevTools/npm-publish@v1
        with:
          token: ${{ secrets.NPM_TOKEN }}
          access: "public"